import Head from 'next/head'
import Header from './components/header'
import Landing from './components/landing'

export default function Home() {

  return (
    <div>
      <Head>
        <title>RealEmpire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <main>
        <Header />
        <Landing />
      </main>
    </div>
  )
}
