import Head from 'next/head'
import Header from './components/header'
import Landing from './components/landing'
import About from './components/about'
import Project from './components/project'

export default function Home() {

  return (
    <div>
      <Head>
        <title>RealEmpire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <main className='snap-y snap-mandatory h-screen overflow-y-scroll' >
        <Landing />
        <About />
        <Project />
      </main>
    </div>
  )
}
